# -*- coding: utf-8 -*-
"""datastructures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqAsWN2U3Glffls7yu89YkzdOnrRjos-
"""

#list(liste)
x=["btc","etc","xrp"]
print(type(x))
#Sözlük((Dictionary)
x={"name":"Peter","Age":34}#key,value
print(type(x))
#Tuple(demet)
x=("python","ml","dl")
print(type(x))
#Set
x={"python","ml","dl"}
print(type(x))
#numbers
a=243456789895434890
print(a)
b=13345677890
print(b)
c=a*b
print(c)
t=1234567788938890723467678
print(float(t))
#######
#multiline string(çok satırlı karakterr  dizileri)
######
long_str="""veri yapıları:Hızlı özet,
sayılar(Numbers):int,float,complex,
karakter Dizileri(Strings):str,
List,Dictionary,Tuple,Set,
Boolean(TRUE-FALSE):bool"""
##indexing in strings
c="name"
print(c[0])
print(c[3])
print(c[0:2])

long_str
print("veri" in long_str)
print("Veri" in long_str)
#####String (Karakter Dizileri) Methods
print(dir(str))
#len
name="john"
print(type(name))
print(len(name))
#upper() lower():küçük-büyük dönüşümleri
print("miuul".upper())
print("miuul".lower())
#replace:karakter değiştirir
hi="Hello AI Era"
print(hi.replace("l","p"))
#split:böler

"Hello AI Era".split()

#strip:kırpar
"ofofo".strip()
"ofofo".strip("o")

#capitalize:İlk harfi büyütür
"foo".capitalize()

dir("foo")

"foo".startswith("f")

##################
#List(Liste)
#################

#-Değiştirilebilir
#-Sıralıdır.Index işlemleri yapılabilir.
#-kapsayıcıdır.

notes=[1,2,3,4]
type(notes)

names=["a","b","v","d"]

not_nam=[1,2,3,"a","b",True,[1,2,3]]
not_nam[0]
not_nam[5]
not_nam[6]
not_nam[6][1]
type(not_nam[6])

type(not_name[6][1])

dir(notes)

len(notes)

len(not_nam)

#append:eleman eklemek için kullanılır
notes
notes.append(100)

#pop:index'e göre eleman siler
notes.pop(0)

#insert:index'e göre ekler

 notes.insert(2, 99)#2index'e 99'u gir

#########################
#Sözlük(Dictionary)
########################

#Değiştirilebilir.
#Sırasız.(3.7 sonra sıralı)
#Kapsayıcı

#key-value

dictionary={"REG":"Regression",
            "LOG":"Logistic Regression",
            "CART":"Classifiction and REG"}
dictionary["REG"]
dictionary={"REG":["RMSE", 10],
           "LOG":["MSE", 20],
           "CART":["SSE", 30]}
dictionary={"REG":10,
            "LOG":20,
            "CART":30}
dictionary["CART"]

#Key Sorgulama
"REG" in dictionary

dictionary.get("REG")

dictionary["REG"]=["YSA",10]

dictionary.keys()

dictionary.values()

dictionary.items()

dictionary.update({"REG":11})

#Tuple(Demet)

#-Değiştirilemez.
#-sıralıdır.
#-Kapsayıcıdır.

t=("john","mark",1,3)
type(t)

t[0]

t[0:3]

t=list(t)

t=tuple(t)

#Set

#-değiştirilebilir
#-Sırasız +Eşsizdir.
#-Kapsayıcıdır.

#differnce():iki kümenin farkı
set1=set([1,2,5])
set2=set([1,2,3])
#set1'de olup set2'de olmayanlar.
set1.difference(set2)

#set1'de olup set2'de olmayanlar
set2.difference(set1)

set1.intersection(set2)

set2.intersection(set1)

set1&set2

set1.union(set2)

#isdisjoint():İki kümenin kesişimi boş mu?
set1=set([7,8,9])
set2=set([5,6,7,8,9,10])

set1.isdisjoint(set2)
set2.isdisjoint(set1)

#issubset:Bir küme diğer kümenin alt kümesi mi?
set1.issubset(set2)

#issuperset():Bir küme diğer kümeyi kapsıyor mu?
set1.issuperset(set2)

set2.issuperset(set1)

