# -*- coding: utf-8 -*-
"""json_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISstFvAdim_Rw9dZL1Fe-dWKez441cmR
"""

import json
import os

DOSYA_ADI = "rehber.json"

def json_yukle():
    if not os.path.exists(DOSYA_ADI):
        with open(DOSYA_ADI, "w") as f:
            json.dump([], f)
    with open(DOSYA_ADI, "r") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []

def json_kaydet(rehber):
    with open(DOSYA_ADI, "w") as f:
        json.dump(rehber, f, indent=4)

def kisi_ekle(ad, telefon, email=None):
    rehber = json_yukle()
    try:
        if not telefon.isdigit():
            print("Telefon sadece rakam içermeli!")
            return
        if email and "@" not in email:
            print("Geçersiz e-posta!")
            return
        rehber.append({"ad": ad, "telefon": telefon, "email": email})
        json_kaydet(rehber)
        print(f"{ad} rehbere eklendi.")
    except Exception as e:
        print("Hata oluştu:", e)

def listele():
    rehber = json_yukle()
    if not rehber:
        print("Rehber boş.")
        return
    for i, kisi in enumerate(rehber, 1):
        print(f"{i}. Ad: {kisi['ad']}, Telefon: {kisi['telefon']}, Email: {kisi.get('email', '-')}")

def ara(ad):
    rehber = json_yukle()
    bulunan = [kisi for kisi in rehber if ad.lower() in kisi['ad'].lower()]
    if not bulunan:
        print("Kişi bulunamadı.")
        return
    for kisi in bulunan:
        print(f"Ad: {kisi['ad']}, Telefon: {kisi['telefon']}, Email: {kisi.get('email', '-')}")

def sil(index):
    rehber = json_yukle()
    try:
        if 0 < index <= len(rehber):
            kisi = rehber.pop(index-1)
            json_kaydet(rehber)
            print(f"{kisi['ad']} rehberden silindi.")
        else:
            print("Geçersiz indeks.")
    except Exception as e:
        print("Hata oluştu:", e)

def disari_aktar_csv():
    rehber = json_yukle()
    csv_dosya = input("Dışarı aktarılacak CSV dosya adı (örnek: rehber.csv): ")
    try:
        with open(csv_dosya, "w") as f:
            f.write("ad,telefon,email\n")
            for kisi in rehber:
                email = kisi.get("email", "")
                f.write(f"{kisi['ad']},{kisi['telefon']},{email}\n")
        print(f"Rehber {csv_dosya} olarak dışarı aktarıldı.")
    except Exception as e:
        print("Hata oluştu:", e)

def iceri_aktar_csv():
    csv_dosya = input("İçe aktarılacak CSV dosya adı: ")
    rehber = []
    try:
        with open(csv_dosya, "r") as f:
            next(f)  # başlık satırı
            for line in f:
                ad, telefon, email = line.strip().split(",")
                rehber.append({"ad": ad, "telefon": telefon, "email": email if email else None})
        json_kaydet(rehber)
        print(f"{csv_dosya} dosyası rehbere aktarıldı.")
    except FileNotFoundError:
        print("CSV dosyası bulunamadı.")
    except Exception as e:
        print("Hata oluştu:", e)

# Menü
while True:
    print("\n--- Kişi Rehberi ---")
    print("1. Kişi Ekle")
    print("2. Kişileri Listele")
    print("3. Ada Göre Ara")
    print("4. Numara ile Sil")
    print("5. JSON -> CSV")
    print("6. CSV -> JSON")
    print("0. Çıkış")

    secim = input("Seçiminiz: ")

    if secim == "1":
        ad = input("Ad: ")
        tel = input("Telefon: ")
        email = input("Email (opsiyonel): ")
        email = email if email else None
        kisi_ekle(ad, tel, email)
    elif secim == "2":
        listele()
    elif secim == "3":
        ad = input("Aranacak ad: ")
        ara(ad)
    elif secim == "4":
        try:
            index = int(input("Silinecek kişi numarası: "))
            sil(index)
        except ValueError:
            print("Lütfen geçerli bir sayı girin!")
    elif secim == "5":
        disari_aktar_csv()
    elif secim == "6":
        iceri_aktar_csv()
    elif secim == "0":
        print("Çıkış yapılıyor...")
        break
    else:
        print("Geçersiz seçim!")
