# -*- coding: utf-8 -*-
"""karsılastırma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1J50TZXNGs4caEz-fGHJQF5DJIVAoDY
"""

class sayi:
  def __init__(self, value):
    self.value=value
def max(num1,num2):
  if num1.value>num2.value:
    return num1
  else:
    return num2

num1=int(input("Birinci sayiyi giriniz:"))
num2=int(input("İkinci sayiyi giriniz: "))

a=sayi(num1)
b=sayi(num2)

buyuk=max(a,b)
print("Buyuk sayi: ",buyuk.value)
