# -*- coding: utf-8 -*-
"""python102

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtUsqmxcNN8971fFVIqm4ubsTEWXgG6H
"""

nuray=open("c:\\musteriler\\eylül\\yenisimler.txt","w")
kayitlar="""Nuray lara Açar: 0542563738411\n
murat can kaya:05742353411\n
serenay doğdu:05644235411"""

nuray.write(kayitlar)
nuray.close()

#bunu da kullanabiliriz
try:
  nuray=open("c:\\musteriler\\eylül\\yenisimler.txt","w")
  kayitlar="""Nuray lara Açar: 0542563738411\n
  murat can kaya:05742353411\n
  serenay doğdu:05644235411"""
  nuray.write(kayitlar)
except IOError:
  print("Bir hata oluştu!")
finally:
  nuray.close()

kayitlar="""Nuray lara Açar: 0542563738411\n
murat can kaya:05742353411\n
serenay doğdu:05644235411"""
with open("c:\\musteriler\\eylül\\yenisimler.txt","w") as file:
 file.close()

import sqlite3

with sqlite3.connect("database.db") as baglanti:
  cursor=baglanti.cursor()
  cursor.execute("CREATE TABLE IF NOT EXISTS ogrenciler(id INIT,ad TEXT)")

import threading
kilit=threading.Lock()

with kilit:
  print("Bu kısım aynı anda sadece 1 thread tarafından çalştırılabilir")

import tempfile

with tempfile.TemporaryFile("w+") as tmp:
  tmp.write("GeciciVeri")
  tmp.seek(0)
  print(tmp.read())

class Kaynak:
  def __enter__(self):
      print("kaynak Açılıyor")
      return self
  def __exit__(self, exc_type, exc_value, traceback):
      print("Kaynak kapatılıyor")

with Kaynak() as k:
  print("Kaynak Kullanılıyor")
  """exc_type → hangi tip hata (bardak kırıldı)
exc_value → hata detayı (bardak camdan düştü)
traceback → hangi adımda oldu (sana adım adım rapor)
"""

nuray=open("c:\\musteriler\\eylül\\yenisimler.txt","a")
kayitlar="""Nuray lara Açar: 0542563738411\n
murat can kaya:05742353411\n
serenay doğdu:05644235411"""


nuray.write("\nMuatafa yıldırım\t: 0555 55 55\n")
nuray.close()

kayitlar="""Nuray lara Açar: 0542563738411\n
murat can kaya:05742353411\n
serenay doğdu:05644235411"""

with open("c:\\musteriler\\eylül\\yenisimler.txt","r+") as dosya:
   dosya.read()
   dosya.seek(0)
   dosya.write("\nHasan ferhatoğlu\t:05255243653\n")

kayitlar="""Nuray lara Açar: 0542563738411\n
murat can kaya:05742353411\n
serenay doğdu:05644235411"""

with open("c:\\musteriler\\eylül\\yenisimler.txt","r+") as dosya:
   okunanlar=dosya.readlines()
   okunanlar.insert(2, "\nVeli Ali\t: 0555 666 66 66\n")
   dosya.writelines(okunanlar)

import os
dir(os)

from os import name
print(name)

import sys

sys.path

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dictionary.py
# 
# my_dict={"kitap":"book",
#          "bilgisayar":"computer",
#          "proglamlama":"programing"}
# 
# def search(word):
#   error="{} The word is not in the dictionary"
#   return my_dict.get(word, error.format(word))
# 
#

import dictionary
result=dictionary.search("kitap")
print(result)
