# -*- coding: utf-8 -*-
"""python101.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pp5mh7v01EvbtLxjI_Vktpf5NzPJAudp
"""

print("hello,AI era!")



type(7.65)

type(3.444)

type("Hello guys")

a=19
print(a)

x=3.14
type(x)

n=True
type(n)

c=23<22
print(c)
type(c)

a=[10,80,90,"Greetings!",3.14,True]
type(a)
#list(liste) kullanımı

D={"Name":"Nuray",
   "Age":[18,54],
   "Adress":"Downtown"}
type(D)
#dictinory(Sözlük kullanımı)
#sıralı
#deiştirebilir

#Tuple:demet demek
a=("Machine learnıng","Data Science")
type(a)
a
#değiştirilemez
#sıralıdır

#set:sırasız anlamında/değiştirilemez
n={"Python","Machine Learning","Data Science","Deep Learning","LLM","NLP"}
type(n)
print(n)

x=9
type(x)

m=8j+4
type(m)
#kompleks

#tipleri değiştirme
float(x)

x=10
print(x)

y=49
print(y)

calc=x*y/10
print(calc)
int(calc)

#strings
print("Miuul")#Single quote(çift tırnak) Double quote(Çift tırnak)
print('miuul')#Fark etmez
name="Miuul"
name='miuul'

long_str="""Veri Yapıları ve Tipler:
int,float,str,complex,->numbers
str->Karakter Dizisi
list,tuple,set,dict->Koleksiyonlar
bool->Mantıksal Değer"""
print(long_str)

name
name[0]
name[3]

name[0:3]
long_str[2:7]

long_str
"Veri" in long_str #in içinde demek
"veri" in long_str #yani long str içnde  veri var mı?

dir(str)
text="hello,AI era!"
len(text)#stringin uzunluğu
text.upper()#Büyük harle yaz
text.lower()#Küçük harfle yaz
text.replace("m","u")#karakterleri değiştir

text.upper().replace("L","A")#metodlar arka arkaya kullanılanılabilinir
text.upper().replace("l","a")
print("1.Change:",text.upper().replace("L","A"))
print("2.Change:",text.upper().replace("l","a"))

text.split() #stringi böler
text.capitalize()#ilk harfi büyük yazmayı sağlar
print("stringi böl:",text.split())
print("Stringi değiştir:",text.capitalize())

lst=["AI","MACHINE LERANING","DATA SCIENCE",101,True]
len(lst)
lst[0]
lst[2]
print("Listenin uzunluğu: ",len(lst))
print("lst[0]:",lst[0])
print("lst[2]:",lst[2])

lst.append(3.14)#listeye eleman ekler
print(lst)

lst.pop(2)#index'e göre eleman siler
print(lst)

lst.insert(1,"Scikt learn")
print(lst)

def multiply_five(number):
          print(number*5)

multiply_five(8)

def sum_eight(number):
        print(number+8)
sum_eight(50)

def hi(word="Hello"):
      print(word,"everyone")
      hi(word)

def diff(num1, num2):
    result=num1-num2
    return result

diff(num1=18, num2=7)

def differnce(num1, num2):
    result=num1-num2
    print(result)
x=diff(num1=18,num2=27)
print(x)

def differnce(num1, num2=2222):
    result=num1-num2
    return result
diff(6789,4453)

#function
#DRY->DON'T REPEAT YOURSELF(KENDİ KENDİNİ TEKAR ETMEZ)!

#Öğrencilerin vize notlarını %40'ını,final notlarının %60'ını ağrırlık alan bir fonksiyon

ogr1=(40*0.4+60*0.6)
ogr2=(30*0.4+70*0.6)
print(ogr1, ogr2)

def note_calculator(midterm,final):
    return (midterm*0.4+final*0.6)
ogr1=note_calculator(40,60)
ogr2=note_calculator(30,70)
print(ogr1,ogr2)

def calculate_Average(midterm,final):
    return midterm*0.4+final*0.6
students=[
   {"name":"Nuray","midterm":35,"final":70},
   {"name":"Lara","midterm":43,"final":90}
]
for student in students:
    avg=calculate_Average(student["midterm"],student["final"])
    print(f"{student['name']}avarage:{avg}")

name="Furkan"
if name=="Vahit":
  print("Name is Vahit")
else :
  print("Name is Furkan")

name=="Furkan"
if name=="Furkan":
  print("Name is Furkan")
elif name=="Vahit":
  print("Name is Vahit")
else:
  print("Name is not Furkan or Vahit")

#Loops
bootcamps=["Data analystic","Machine learning","AWS Cloud engineer"]
for bc in bootcamps:
  print(bc)
for bc in bootcamps:
  print(bc.upper())
for bc in bootcamps:
  print(bc.lower())
for bc in bootcamps:
  print(bc.title())
for bc in bootcamps:
  print("Data analystic".replace("D","a"))

notes=[30,40,50]
for note in notes:
     print(note)

for note in notes:
    print(int (1.5*(note+10)))
def extra_notes(note, extra_point):
    new_note=int(1.5*(note+extra_point))
    if new_note>100:
      new_note=100
    return new_note

extra_notes(30, 10)
extra_notes(50, 30)


for note in notes:
    print("old grade:",note)
    print("new grade:",extra_notes(note,10))
    print("-------------------")

#while loop
num=5
while num<10:
  print(num)
  num=num+1
idx=0
while idx<len(notes): #idx sayaç değişkeni #notes listesinden küçük olduğu sürec
  note=notes[idx]
  print("old grade: ",note)
  print("new grade: ",extra_notes(note,10))
  print("------------")
  idx+=1
