# -*- coding: utf-8 -*-
"""SelectionSort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HAGUD5-e09-KYX_k-ABX4Xifiw_ZHgew
"""

def selection_sort(arr):
  n=len(arr)
  for i in range(n-1):
    min_ındex=i
    for j in range(i+1, n):
      if arr[j]<arr[min_ındex]:
        min_ındex=j

    arr[i], arr[min_ındex]=arr[min_ındex], arr[i]
arr=[64,25,12,22,11]
selection_sort(arr)
print("Sorted array: ",arr)
