# -*- coding: utf-8 -*-
"""ds_homework

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXPHLOg2s47Qe_dg19kWRx3EtwKT3FJT
"""

# 1. Kullanıcıdan metin alma
metin = input("Lütfen bir metin giriniz: ")

# 2. Metni küçük harfe çevirme
metin = metin.lower()

# 3. Noktalama işaretlerini temizleme
isaretler = ".,;:!?\"'()[]{}"
for i in isaretler:
    metin = metin.replace(i, "")

# 4. Kelimeleri ayırma
kelimeler = metin.split()

# 5. Her kelimenin kaç kez geçtiğini sayma
kelime_sayilari = {}
for kelime in kelimeler:
    if kelime in kelime_sayilari:
        kelime_sayilari[kelime] += 1
    else:
        kelime_sayilari[kelime] = 1

# 6. En çok geçen kelimeyi bulma
en_cok_gecen_kelime = max(kelime_sayilari, key=kelime_sayilari.get)
en_cok_gecen_sayi = kelime_sayilari[en_cok_gecen_kelime]

# 7. Toplam harf sayısını bulma
harf_sayisi = sum(c.isalpha() for c in metin)

# 8. Sonuçları ekrana yazdırma
print("\nKelime sayıları:", kelime_sayilari)
print(f"En çok geçen kelime: '{en_cok_gecen_kelime}' ({en_cok_gecen_sayi} kez)")
print(f"Metindeki toplam harf sayısı: {harf_sayisi}")

isimler = ["ali","osman","hasan"]
notlar1 = [70,80,45,100]
notlar2 = [60,85,55,90,20]
#zip ile birleştirme(kısa olan listeye göre keser)
birlesik=zip(isimler,notlar1,notlar2)

#{isim: ortalama} dist olusturma
ortalama_dict={}
for isim, n1, n2 in birlesik:
 ortalama=(n1+n2)/2
 ortalama_dict[isim]=ortalama

print("öğr. ortalamaları:",ortalama_dict)

#en yüksek ve en dusuk ortalam
en_yuksek=max(ortalama_dict,key=ortalama_dict.get)
en_dusuk=min(ortalama_dict,key=ortalama_dict.get)
print(f"en yüksek ortalama: {en_yuksek} ({ortalama_dict[en_yuksek]})")
print(f"en dusuk ortalama: {en_dusuk}   ({ortalama_dict[en_dusuk]})")

#sınıf ortalaması
sinif_ort=sum(ortalama_dict.values())/len(ortalama_dict)
print("Sınıf Ortalaması:",sinif_ort)

#ortalamsı 50'nin altında olanlar
dusuk_ortalama_set={isim for isim, ort in ortalama_dict.items() if ort<50}
print("50'nin altında olan öğrenciler:",dusuk_ortalama_set)

# Ürün ve fiyat bilgilerini dictionary olarak tutalım
urunler = {
    "elma": 10,
    "armut": 12,
    "ekmek": 5,
    "süt": 15,
    "peynir": 25,
    "çikolata": 20
}

# Kullanıcının sepeti
sepet = {}

while True:
    urun = input("Sepete eklemek istediğiniz ürünü yazın (bitirmek için 'q'): ").lower()
    if urun == 'q':
        break
    if urun not in urunler:
        print("Maalesef bu ürün marketimizde yok.")
        continue
    try:
        miktar = int(input(f"{urun} için miktar girin: "))
    except ValueError:
        print("Lütfen geçerli bir sayı girin.")
        continue

    if urun in sepet:
        sepet[urun] += miktar
    else:
        sepet[urun] = miktar

# Sepet toplamını hesaplayalım
toplam = sum(urunler[urun] * miktar for urun, miktar in sepet.items())

# İndirim uygulama
indirim = 0
if toplam > 500:
    indirim = toplam * 0.10
    toplam = toplam - indirim

# Sepet içeriğini ve toplamı yazdıralım
print("\n--- Sepetiniz ---")
for urun, miktar in sepet.items():
    print(f"{urun.capitalize()}: {miktar} x {urunler[urun]} TL = {urunler[urun] * miktar} TL")
print(f"İndirim: {indirim} TL")
print(f"Toplam tutar: {toplam} TL")

# Kitap-öğrenci eşleşmesini tutacak sözlük
kitap_odunc = {}

while True:
    # Kullanıcıdan giriş al
    kitap = input("Kitap adı (çıkmak için 'q'): ").strip()
    if kitap.lower() == 'q':
        break

    # Eğer kullanıcı iade yapmak istiyorsa
    if kitap.lower() == 'iade':
        kitap_iade = input("İade edilecek kitap adı: ").strip()
        if kitap_iade in kitap_odunc:
            del kitap_odunc[kitap_iade]
            print(f"{kitap_iade} iade edildi.")
        else:
            print("Bu kitap ödünç listesinde yok.")
        continue

    # Kitap zaten ödünç verilmiş mi kontrol et
    if kitap in kitap_odunc:
        print(f"Üzgünüz, '{kitap}' zaten {kitap_odunc[kitap]} adlı öğrenciye verilmiş.")
        continue

    ogrenci = input("Öğrenci adı: ").strip()
    kitap_odunc[kitap] = ogrenci
    print(f"'{kitap}' kitabı {ogrenci} adlı öğrenciye ödünç verildi.")

# Program bittiğinde istatistikleri yazdır
farkli_kitap_sayisi = len(kitap_odunc)
farkli_ogrenci_sayisi = len(set(kitap_odunc.values()))

print("\nProgram sonlandı.")
print(f"Toplam farklı ödünç verilen kitap sayısı: {farkli_kitap_sayisi}")
print(f"Toplam farklı öğrenci kitap almış: {farkli_ogrenci_sayisi}")

# Katılımcıları saklayacağımız liste
katilimcilar = []

while True:
    ad = input("Katılımcı adı (çıkmak için 'q'): ")
    if ad.lower() == 'q':
        break

    try:
        yas = int(input("Yaş: "))
        boy = float(input("Boy (m): "))
    except ValueError:
        print("Lütfen geçerli sayı giriniz!")
        continue

    sehir = input("Şehir: ")

    # Tuple olarak kaydet
    katilimci = (ad, yas, boy, sehir)
    katilimcilar.append(katilimci)

# Kayıt sayısı
print("\nToplam katılımcı sayısı:", len(katilimcilar))

if katilimcilar:
    # Boy ortalaması
    toplam_boy = sum(k[2] for k in katilimcilar)
    boy_ort = toplam_boy / len(katilimcilar)
    print("Katılımcıların boy ortalaması: {:.2f} m".format(boy_ort))

    # En yaşlı ve en genç
    yaslar = [k[1] for k in katilimcilar]
    en_genc_yas = min(yaslar)
    en_yasli_yas = max(yaslar)
    print("En genç katılımcı yaşı:", en_genc_yas)
    print("En yaşlı katılımcı yaşı:", en_yasli_yas)

    # En genç ve en yaşlı katılımcı isimleri
    en_genc = [k[0] for k in katilimcilar if k[1] == en_genc_yas]
    en_yasli = [k[0] for k in katilimcilar if k[1] == en_yasli_yas]
    print("En genç katılımcı(lar):", ", ".join(en_genc))
    print("En yaşlı katılımcı(lar):", ", ".join(en_yasli))

    # Farklı şehir sayısı
    sehirler = set(k[3] for k in katilimcilar)
    print("Farklı şehir sayısı:", len(sehirler))