# -*- coding: utf-8 -*-
"""insertion_sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NLSeZ-5nERkYXJhVT5SQBlZjMmoPqWz
"""

def insertion_sort(arr):
  for i in range(1,len(arr)):
    key=arr[i]
    j=i-1
    while j>=0 and arr[j]>key:
      arr[j+1]=arr[j]
      j-=1
    arr[j+1]=key
arr=[12,11,13,5,6]
insertion_sort(arr)
print("Sorted Array: ",arr)