# -*- coding: utf-8 -*-
"""pandas/series

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-Q_YyxVeE8SGyJ51TzIiEOgUIRdN05K
"""

!pip install numpy

import numpy as  np

list=[1,2,3,4,5,6,7,8]
list

list2=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
list2

np.array([[1,2,3,4],
       [5,6,7,8],
       [9,10,11,12]])

print(list2.shape) #shape boyut bilgisini verir
print(list2.size)

list3=np.arange(10)# ArrayRANGE normalde range'tir arraylerde arange
list3 #0'dan 9 a kadar

list3=list3.reshape(2,5)#re shape yeniden şekilendirmekdemek
list3# 2 satır ve 5 sütundan oluşacak

random_matris=np.random.randint(20,70,15) #random->rastgele sayılar (low,high,size)
#20 ile 70 arasında (dahil değiller) 15 tane üret
random_matris=random_matris.reshape(5,3) #5 satır 3 sütundan oluşsun
random_matris

print("Aritmetik:\t",np.mean(random_matris))
print("Medyan:\t\t",np.median(random_matris))
print("Varynas:\t",np.var(random_matris))
print("Stanadrt sapma:\t",np.std(random_matris))

import numpy as np
import pandas as pd

pd.Series([10,20,30,40,50])

data=np.array([10,20,30,40,50])
seri=pd.Series(data,index=[201,202,203,204,205])
seri

data={'a':0,'b':1,'c':2,'d':3}

seri=pd.Series(data)
seri

seri[0]

seri[0:5]

seri[0:4]

seri['a']

seri[['a','b','c']]

seri['a':'d']

seri.sum()

seri.median()

seri.max()

seri.mean()

print("Letter İndex Series:\n",seri,"\n")

print("Letter Index Series:\n",seri,"\n")
print("seri['a']:\n",seri['a'])
print("seri[['a','b','c']]:\n",seri[['a','b','c']])
print("seri['a':'d']:\n",seri['a':'d'])
print("seri.sum():\n",seri.sum())
print("seri.median():\n",seri.median())
print("seri.max():\n",seri.max())
print("seri.mean():\n",seri.mean())

!pip install pandas

import pandas as pd
import numpy as np

names=["Nuray","Lara","Sabiha","Cem","Emre"]

df=pd.DataFrame(names,columns=["names"])
df

data={'Sehirler':['Ankara','Bursa','Denizli','Eskisehir'],
      'Plakalar':[6,16,20,26]}
data

df=pd.DataFrame(data,index=['a','b','c','d'])
df

df["havadurumu"]=pd.Series([33,26,40,26],index=['a','b','c','d'])
df["havadurumu"]

for col in df.columns:
   print(f"'{col}")

print(df.columns.tolist()) #listenin tanımlı olup olmadığını kontrol ediyoruz

print(df.columns)

df["havadurumu"]=pd.Series([33,26,40,26],index=['a','b','c','d'])
print(df["havadurumu"])
df.drop('havadurumu',axis=1,inplace=True)#df.drop silmeye yarıyor
print(df)

from google.colab import files
files.upload()

import matplotlib.pyplot as plt
import pandas as pd

data=pd.read_csv("house_prices.csv")
data.head()

data.tail()

data_head_100=data.head(100)

plt.plot(data_head_100.datesold,data_head_100.price)

plt.xticks(rotation=90)
plt.show()