# -*- coding: utf-8 -*-
"""python101

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxDnpDnsM4l6Oak42ChYWfdMUvmOpC98
"""

age=25;
age+=0.5;
print(age,type(age));

name=input('Name:');
print('Greetings',name);

celsius=18
if celsius>20:
  print("Good ")

celsius =18
if celsius>20: #if koşulunda : yazılır sonra girinti bloğu yazılır ve 4 karakter boşluk olmalıdır
    print("Good")
else :
    print("Not Good")





celsius=20;
if celsius>25:
    print("Hot");
elif celsius<20:
    print("Cold");
else:
    print("Comfortable");

numbers={1,2,3,4,5,6,7,8,9,10}
for i in numbers:
 print(i)

for i in range(4,225):#for da da: olur ve sontra 4 Girinti olur ama dikakat et ya 1 girinti kullanırsın hepsinde ya 1
    if i%5==0:
        print(i)
    print("Loop is completed")

import time
celsius=15

while celsius<40:
 if -273<celsius<20:
  print("Cold")
 elif 20<=celsius<25:
  print("Good")
 elif celsius>=25:
  print("Hot")
 else :
  print("Something went wrong")

 print("The temperature is: ",celsius)
 celsius+=5
 time.sleep(1)

for i in range(9,225):
    if i% 5==0 :
     print(i)



import time
import sys
print("Loading",end="")

for i in range(5):
  print(".",end="",flush=True)
  time.sleep(1)
print("\nYükleme tamamlandı!")

import random
while True: #while True sonsuz kadar devam eder
 random_number=random.randrange(1000) #ramdom.randrange kalıp bunu bil
 print(random_number)#tırnak kullanılmaz  yazdırmıyoruz bunu öyle düşün

 if random_number==777:
  print('Found!')
 break





names={'Ayşe','Fatma','George','Lara','Nuray','Can','Mert',18}
for name in names:
 if type(name)!=str:
  print('Found',name)
 else:
  print(name,'is a string')

print("True or True:",True or True);
print("True or False:",True or False);
print("False or True:",False or True);
print("False or False:",False or False);

print("not True:",not True);
print("not False:",not False);

import math
floor_number=(math.floor(3.14));
print(floor_number,type(floor_number));

import random;
print(random.randint(100,200));

import datetime;
print(datetime.datetime.now());

name='NURAY LARA';
print('Hello',name);

name='NURAY LARA';
print(name);

print("Hello World!");

def sum(num1,num2):
  answer=num1+num2
  return answer

result=sum(12,5)
print(result)

number=18
def change_number():
  global number
  number=4
change_number()
print(number)

def sum(a,b):
 return a+b

print(sum(3,4))

x=20
def change():
  x=50
change()
print(x)

x=59
def change_global():
   global x #global değişkenler önceden değer veririm fonksşyonun dışında ben sonra değiştirmek isterim o zaman kullanırım
   x=19


change_global()
print(x)

def greetings(name):
  message="Hello "+name
  print(message) #Local değişkenler ise içerideki bir değeri değiştirmek iiçin
  #kullanırım bunu
greetings("Nuray")

!pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt#matplotlib kütüp. görselleştirmek için kul.

data=[10,20,20,40,50,60,70]

sns.lineplot(x=range(7),y=data)
plt.show()

shopping_list=["Apple","Juice","Ball","Book"]

shopping_list.append("Water") #append eklemek demek
print(shopping_list)

shopping_list.insert(2,"Banana")#insert eklemek burada 2.index e bananayı koydu
print(shopping_list)

shopping_list.remove("Apple")
print(shopping_list)

number_list=[23,298,765,987]

square_list=[]

for num in number_list:
  square_list.append(num**2)

print(square_list)

shoppping_list=("Apple","Juiece","Ball","Book")

item1,item2,item3,item4=shopping_list
print(item1)
print(item2)
print(item3)
print(item4)

print(shoppping_list[3])

print(shopping_list[0:3])

inventory=dict()
inventory['bananas']=25
inventory['Apples']=102
inventory['oranges']=54
inventory['watermelons']=4

print(inventory.keys())

print(inventory.values())

print(inventory.items())

for key in inventory:
   inventory[key]+=100
print(inventory)

inventory=dict()
inventory['bananas']=25
inventory['apples']=102
inventory['oranges']=54
inventory['watermelons']=4

for element in inventory:
 print(element)

for key in inventory:
  inventory[key]+=100
  print(inventory)

for key,value in inventory.items(): #items hem değer hem de anahtarlara erişiriz
 if value>200:
  print("Too many",key)
 else:
  print("Enough",key)

python_file=open("python.txt","w")#write(yazma) dosyalam işlemlerini kaydetmek için kullanırız
python_file.write("Hello World,this is a python")
python_file.close() #close kapatmak çin kullanırız

import random

with open("number_history.txt","w") as numbers_file:
#with açılan kaynak  kodunu otomatik açma/kapamayı sağlar
#as açılan kaynak kodunu bir neseneye atar
#with-as ifadesi işlemi bitince otomatik kapanan bir yapı

   while True:
      random_number=random.randrange(1000)
      print(random_number)
      numbers_file.write(str(random_number)+"\n")
      if random_number==777:
         print("Found!")
         numbers_file.write("Found!")
         break

def  divide(number1, number2):
   try:
      number1_integer=int(number1)
      number2_integer=int(number2)
      return number1_integer/number2_integer
   except ValueError:
      return 'Only integers are allowed! Try again.'
   except ZeroDivisionError:
      return "You cannot divide any number by zero!"
number1=input("Please provide a numbers1: ")
number2=input("PLease provide a numbers2: ")

print(divide(number1, number2))